import type { PlanRow } from "./types";

export const plansSeed: PlanRow[] = [
  {
    id: 1,
    name: "NBN Standard",
    details: "Perfect for households with basic internet needs",
    type: "NBN",
    speedOrData: "25/5 Mbps",
    price: "$69.95/Month",
    status: "Published",
    customers: 1234,
  },
  {
    id: 2,
    name: "NBN Premium",
    details: "Ideal for streaming and working from home",
    type: "NBN",
    speedOrData: "100/20 Mbps",
    price: "$89.95/Month",
    status: "Published",
    customers: 892,
  },
  {
    id: 3,
    name: "Mobile 20GB",
    details: "Great for moderate mobile usage",
    type: "Mobile",
    speedOrData: "4G/5G",
    price: "$29.95/Month",
    status: "Published",
    customers: 567,
  },
  {
    id: 4,
    name: "Mobile Unlimited",
    details: "Unlimited everything for heavy users",
    type: "Mobile",
    speedOrData: "4G/5G",
    price: "$49.95/Month",
    status: "Draft",
    customers: 0,
  },
  {
    id: 5,
    name: "NBN Business Pro",
    details: "High-speed internet for businesses",
    type: "NBN",
    speedOrData: "250/25 Mbps",
    price: "$149.95/Month",
    status: "Published",
    customers: 156,
  },
];
